style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  AlsoCouldBeApply:
    active: true
  CanBeNonNullable:
    active: true
  CascadingCallWrapping:
    active: true
  CollapsibleIfStatements:
    active: true
  ExpressionBodySyntax:
    active: true
    includeLineWrapping: true
  WildcardImport:
    active: true

formatting:
  active: true
  NoWildCardImport:
    active: true

naming:
  FunctionNaming:
    active: true
    functionPattern: '^([a-zA-Z$][a-zA-Z$0-9]*)|(`.*`)$'

performance:
  UnnecessaryTemporaryInstantiation:
    active: true

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: '_|(ignore|expected).*'
  EmptyClassBlock:
    active: true
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptyKtFile:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true
