version: '3.9'
services:
  postgres:
    container_name: "postgres"
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saga
  dbeaver:
    container_name: "dbeaver"
    image: dbeaver/cloudbeaver:latest
    ports:
      - "9090:8978"
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    environment:
      - SERVICES=sqs,sns
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./build/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "4566:4566"
