spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saga
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    stack.auto: false
    region:
      auto: false
      static: us-east-1
    credentials:
      access-key: localstack
      secret-key: localstack
    endpoint: "http://localhost:4566"
    sqs.queues:
      create-saga: "saga-create-saga-command-queue"
      create-trip-command: "saga-create-trip-command-queue"
      create-trip-response: "saga-create-trip-response-queue"
      update-events: "saga-update-events-queue"
      create-hotel-reservation-command: "saga-create-hotel-reservation-command-queue"
      create-hotel-reservation-response: "saga-create-hotel-reservation-response-queue"
      create-flight-reservation-command: "saga-create-flight-reservation-command-queue"
      create-flight-reservation-response: "saga-create-flight-reservation-response-queue"
    sns.topics:
      saga-events: "saga-saga-events-topic"
