spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saga
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
